#!/usr/bin/env sh

mouse_name="HID 1bcf:08a0 Mouse"
touchpad_name="SYNA32B8:00 06CB:CE7D Touchpad"

xinput set-prop "$mouse_name" "libinput Accel Speed" "-1"
xinput set-prop "$touchpad_name" "libinput Tapping Enabled" "1"
xinput set-prop "$touchpad_name" "libinput Tapping Enabled Default" "0"
xinput set-prop "$touchpad_name" "libinput Tapping Drag Enabled" "1"
xinput set-prop "$touchpad_name" "libinput Tapping Drag Enabled Default" "1"
xinput set-prop "$touchpad_name" "libinput Tapping Drag Lock Enabled" "0"
xinput set-prop "$touchpad_name" "libinput Tapping Drag Lock Enabled Default" "0"
xinput set-prop "$touchpad_name" "libinput Tapping Button Mapping Enabled" "1, 0"
xinput set-prop "$touchpad_name" "libinput Tapping Button Mapping Default" "1, 0"
xinput set-prop "$touchpad_name" "libinput Natural Scrolling Enabled" "1"
xinput set-prop "$touchpad_name" "libinput Natural Scrolling Enabled Default" "0"
xinput set-prop "$touchpad_name" "libinput Disable While Typing Enabled" "1"
xinput set-prop "$touchpad_name" "libinput Disable While Typing Enabled Default" "1"
xinput set-prop "$touchpad_name" "libinput Scroll Methods Available" "1, 1, 0"
xinput set-prop "$touchpad_name" "libinput Scroll Method Enabled" "1, 0, 0"
xinput set-prop "$touchpad_name" "libinput Scroll Method Enabled Default" "1, 0, 0"
xinput set-prop "$touchpad_name" "libinput Accel Speed" "0.000000"
xinput set-prop "$touchpad_name" "libinput Accel Speed Default" "0.000000"
xinput set-prop "$touchpad_name" "libinput Accel Profiles Available" "1, 1"
xinput set-prop "$touchpad_name" "libinput Accel Profile Enabled" "1, 0"
xinput set-prop "$touchpad_name" "libinput Accel Profile Enabled Default" "1, 0"
xinput set-prop "$touchpad_name" "libinput Left Handed Enabled" "0"
xinput set-prop "$touchpad_name" "libinput Left Handed Enabled Default" "0"
xinput set-prop "$touchpad_name" "libinput Send Events Modes Available" "1, 1"
xinput set-prop "$touchpad_name" "libinput Send Events Mode Enabled" "0, 0"
xinput set-prop "$touchpad_name" "libinput Send Events Mode Enabled Default" "0, 0"
xinput set-prop "$touchpad_name" "Device Node" "'/dev/input/event13'"
xinput set-prop "$touchpad_name" "Device Product ID" "2, 7"
xinput set-prop "$touchpad_name" "libinput Drag Lock Buttons" "<no items>"
xinput set-prop "$touchpad_name" "libinput Horizontal Scroll Enabled" "1"
